### ISSUE TITLE
Resources deleted from Transifex

### ISSUE THREAD

**Issue by emmapeel2** [arthuredelstein/torpatches#1]
https://github.com/arthuredelstein/torpatches/blob/cfe158e43767442425fe51d4f069f95eb22f504e/src/torpatches/translations.clj#L27

Ey there: 
This support resources  have been deleted from transifex.
Now Support - portal has all the strings the previous support-* had.

Maybe you want to replace them with support-portal

**Comment by arthuredelstein** [comment]
Fixed by 5b8472e
