### ISSUE TITLE
Please add the translations for the new tpo homepage to the stats

### ISSUE THREAD

**Issue by emmapeel2** [arthuredelstein/torpatches#10]
The new Tor Project website is being translated at https://www.transifex.com/otf/tor-project-support-community-portal/tpo-contentspot/ and could very much do with stats like those you provide for the tb-manual and the support portal.

Thanks in advance!

**Comment by arthuredelstein** [comment]
Added: https://torpat.ch/tpo-locales
fce2557e0686b5d097bd9d9a805d197773080484
