### ISSUE TITLE
File chrome/locale/en/browser.properties not translatable anymore

### ISSUE THREAD

**Issue by emmapeel2** [arthuredelstein/torpatches#2]
https://github.com/arthuredelstein/torpatches/blob/cfe158e43767442425fe51d4f069f95eb22f504e/src/torpatches/translations.clj#L21

This file has been deleted from master at
https://gitweb.torproject.org/torbutton.git/commit/src/chrome/locale/en/browser.properties?id=fc91b515a6e0d9e5455d39e52abf2c1352e20f3c

because:
"To keep the browser.startup.homepage pref value out of translators hands, all of the localized browser.properties files have been removed and the pref value (about:tor) has been moved to a new non-localized.properties file. We no longer provide a value for spellchecker.dictionary, which means non en-US users will probably need to set their spellchecking language from the browser context menu or via about:config after they install a dictionary for their language. The browser will also consult the LANG environment variable and use a "default default" of en-US if an en-US dictionary is installed."

**Comment by arthuredelstein** [comment]
Thanks! Fixed by cfba26ccacb18ff9790b6bd6cfc9ea542c334616
