### ISSUE TITLE
move torbutton components en to en-US

### ISSUE THREAD

**Issue by emmapeel2** [arthuredelstein/torpatches#6]
we have moved the name of some locales on the translation.git repo, so we should check if torpat is picking them up well.
the most important is en -> en-US but for example in https://torpat.ch/locales i see that bn looks like not deployed in firefox and so something may need to be changed.

**Comment by arthuredelstein** [comment]
I fixed the Bangla issue. torpat seems to be handling en_US correctly already.

Thank you for filing these issues and sorry for the delay!
