### ISSUE TITLE
please add the new tb-manual translations to the locale stats

### ISSUE THREAD

**Issue by emmapeel2** [arthuredelstein/torpatches#7]
we have a new resource, https://www.transifex.com/otf/tor-project-support-community-portal/tbmanual-contentspot/ for the Tor Browser manual.

it would be great if you can offer stats of its situation in a similar way to the one shown at https://torpat.ch/support-locales for the different stakeholders of the project to be able to see the situation in a glance...

**Comment by arthuredelstein** [comment]
Hi Emma - Sorry for the delay! I will try to get to this soon. :)

**Comment by emmapeel2** [comment]
No worries arthur, is not urgent. I just leave you here some little procrastination gifts for when you miss us :)

**Comment by arthuredelstein** [comment]
Fixed. Sorry it took me so long!
