### ISSUE TITLE
new file for torbutton: securityLevel.properties

### ISSUE THREAD

**Issue by emmapeel2** [arthuredelstein/torpatches#8]
A new file to fetch stats for: 

the Tor Button has a new file to translate: https://gitweb.torproject.org/torbutton.git/plain/src/chrome/locale/en-US/securityLevel.properties 
It is being translated on transifex at https://www.transifex.com/otf/torproject/torbutton-securitylevelproperties/
It would be great to add it to the tor locales family, so it appears integrated at https://torpat.ch/locales

Thanks!

**Comment by arthuredelstein** [comment]
Sorry it took me so long! Patch works great.
